import numpy as np
a = np.array([0,1,2,3])
print("a =", a)
print("a[1] =", a[1])
print("list(a) =", list(a))
print("type(a) =", type(a))
print("a.dtype =", a.dtype)
print("a.size =", a.size)
print("a.ndim =", a.ndim)
print("a.shape =", a.shape)